[db]
db-dev.localhelp.store

[backend]
backend-dev.localhelp.store

[frontend]
frontend.localhelp.store

[db:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/ec2-user/.ssh/db.pem

[backend:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/ec2-user/.ssh/backend.pem

[frontend:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/ec2-user/.ssh/frontend.pem
