- name: create application user
  become: true
  ansible.builtin.user:
    name: localhelp
    system: true
    create_home: true


- name: install base packages
  become: true
  ansible.builtin.dnf:
    name:
      - java-17-amazon-corretto
      - python3-pip
      - mariadb105
    state: present


- name: install python dependencies for mysql module
  become: true
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3


- name: ensure application directory exists
  become: true
  ansible.builtin.file:
    path: /opt/localhelp/backend
    state: directory
    owner: localhelp
    group: localhelp
    mode: "0755"

- name: Get latest backend snapshot metadata
  ansible.builtin.uri:
    url: "{{ nexus_url }}/repository/{{ component }}/com/localhelp/{{ component }}/{{ app_version }}/maven-metadata.xml"
    return_content: yes
  register: nexus_metadata


- name: Extract latest snapshot jar version
  ansible.builtin.set_fact:
    snapshot_version: "{{ nexus_metadata.content | regex_search('<value>(.*?)</value>', '\\1') | first }}"


- name: Download latest snapshot jar from nexus
  become: true
  ansible.builtin.get_url:
    url: "{{ nexus_url }}/repository/{{ component }}/com/localhelp/{{ component }}/{{ app_version }}/{{ component }}-{{ snapshot_version }}.jar"
    dest: "/opt/localhelp/backend/app.jar"
    owner: localhelp
    group: localhelp
    mode: "0644"


- name: verify downloaded jar
  become: true
  ansible.builtin.command:
    cmd: ls -lh /opt/localhelp/backend/app.jar
  register: jar_check
  changed_when: false


- name: display jar details
  ansible.builtin.debug:
    msg: "{{ jar_check.stdout }}"


- name: copy database schema file
  become: true
  ansible.builtin.copy:
    src: init.sql
    dest: /opt/localhelp/backend/init.sql
    owner: localhelp
    group: localhelp
    mode: "0644"

- name: import database schema
  become: true
  community.mysql.mysql_db:
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    login_host: "{{ login_host }}"
    target: "/opt/localhelp/backend/init.sql"
    state: import
    name: all


- name: deploy systemd service
  become: true
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
    mode: "0644"


- name: reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true


- name: restart backend service
  become: true
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: true