- name: install base packages
  ansible.builtin.dnf:
    name:
      - git
      - java-17-amazon-corretto
      - maven
      - python3-pip
    state: present

- name: install mysql client (MariaDB compatible for AWS Linux)
  ansible.builtin.dnf:
    name:
      - mariadb105
    state: present

- name: install python dependencies for mysql module
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3

- name: create localhelp user
  ansible.builtin.user:
    name: localhelp

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: localhelp
    group: localhelp
    mode: "0755"

- name: run app pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: clone backend repo
  ansible.builtin.git:
    repo: "https://github.com/sbp828/localhelp-backend.git"
    dest: /app
    version: main
    force: yes

- name: build springboot app
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: copy backend service file
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
    mode: "0644"

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: start backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: true

- name: import data into mysql
  community.mysql.mysql_db:
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql
    state: import
    name: all
