---
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy frontend application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Copy nginx configuration
  ansible.builtin.template:
    src: localhelp.conf.j2
    dest: /etc/nginx/default.d/localhelp.conf
  notify:
    - restart nginx