- name: delete app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: clone backend repo
  ansible.builtin.git:
    repo: 'https://github.com/sbp828/localhelp-backend.git'
    dest: "{{ app_location }}"
    version: main
